steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'gcr.io/ecorank-15295/ecorank-api:latest',
      '-f', 'Dockerfile',
      '.'
    ]
    dir: 'backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ecorank-api',
      '--image', 'gcr.io/ecorank-15295/ecorank-api:latest',
      '--region', 'europe-west2',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
