steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '--no-cache', '-t',
      'gcr.io/$PROJECT_ID/github.com/sozbad/ecorank:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '.'
    ]
    dir: 'backend'   # ✅ this is critical

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ecorank-api',
      '--image', 'gcr.io/$PROJECT_ID/github.com/sozbad/ecorank:$COMMIT_SHA',
      '--region', 'europe-west2',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
