steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'gcr.io/$PROJECT_ID/github.com/sozbad/ecorank:$COMMIT_SHA',
      '.'
    ]
    dir: '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'ecorank-api',
      '--image', 'gcr.io/$PROJECT_ID/github.com/sozbad/ecorank:$COMMIT_SHA',
      '--region', 'europe-west2',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
